version: "3.4"
services:
  nethermind_docker:
    image: nethermind/nethermind:latest
    restart: always
    volumes:
      - nethermind_sepolia:/data
      - "./jwtsecret:/data/jwtsecret"
    command: --config sepolia --datadir /data --Network.DiscoveryPort=30303 --Network.P2PPort=30303 --JsonRpc.Enabled=true --JsonRpc.EnabledModules="net,eth,consensus,subscribe,web3,admin" --JsonRpc.Port=8545 --JsonRpc.Host=0.0.0.0 --Merge.Enabled=true --Merge.TerminalTotalDifficulty=58750000000000000000000 --Init.DiagnosticMode="None" --JsonRpc.AdditionalRpcUrls="http://localhost:8545|http;ws|net;eth;subscribe;engine;web3;client|no-auth,http://localhost:8551|http;ws|net;eth;subscribe;engine;web3;client" --JsonRpc.JwtSecretFile /data/jwtsecret --Sync.SnapSync=true
    network_mode: host
    container_name: nethermind_docker

  geth_docker:
    image: ethereum/client-go:stable
    restart: always
    volumes:
      - geth_docker:/data
      - "./jwtsecret:/data/jwtsecret"
    command: --sepolia --datadir /data --http --http.addr "0.0.0.0" --http.api "eth,net,web3" --cache 2048 --maxpeers 30 --authrpc.addr localhost --authrpc.port 8551 --authrpc.vhosts localhost --authrpc.jwtsecret /data/jwtsecret
    network_mode: host
    container_name: geth_docker

  beacon_node:
    image: icon/lodestar:dev
    restart: always
    volumes:
      - beacon_sepolia:/data
      - logs:/logs
      - "./jwtsecret:/data/jwtsecret"
    env_file: .env
    network_mode: host
    command: beacon --dataDir /data --rest --execution.urls http://127.0.0.1:8551 --rest.address 0.0.0.0 --metrics --logFile /logs/beacon.log --logFileLevel debug --logFileDailyRotate 5 --checkpointSyncUrl https://sepolia.checkpoint-sync.ethpandaops.io --jwt-secret /data/jwtsecret --rest.namespace *
    # NodeJS applications have a default memory limit of 2.5GB.
    # This limit is bit tight for a Prater node, it is recommended to raise the limit
    # since memory may spike during certain network conditions.
    environment:
      NODE_OPTIONS: --max-old-space-size=4096

  prometheus:
    build: docker/prometheus
    restart: always
    volumes:
      - "prometheus:/prometheus"

  grafana:
    build: docker/grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "grafana:/var/lib/grafana"
      - "grafana-dashboards:/dashboards"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}

volumes:
  nethermind_docker:
  nethermind_sepolia:
  geth_docker:
  beacon_node:
  beacon_sepolia:
  logs:
  prometheus:
  grafana:
  grafana-dashboards:
